#!/usr/bin/env bash

set -euo pipefail

# Exit code conventions: https://freedesktop.org/software/systemd/man/systemd.exec.html#Process%20Exit%20Codes

# https://stackoverflow.com/a/246128
this_script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

[[ -d "${HOME}/.deep-freeze-backups" ]] || mkdir "${HOME}/.deep-freeze-backups"

timestamp_last_run="${HOME}/.deep-freeze-backups/last_run"
touch "${timestamp_last_run}"

# Check we have Internet access
if ! ping -n -c 1 -q 1.1.1.1 >/dev/null 2>/dev/null; then
    exit 69 # service unavailable
fi

# Check last run was over 24h ago
timestamp_success="${HOME}/.deep-freeze-backups/last_successful_backup"
if [ -e "${timestamp_success}" ]; then
    timestamp=$(date -r "${timestamp_success}" +%s)
    now=$(date +%s)
    if [ $((now - timestamp)) -lt 86400 ]; then
        exit 75 # transient error
    fi
fi

"${this_script_dir}/deep-freeze.py"
touch "${timestamp_success}"
